"""Shared internal data types and stage protocols for the pipeline.

Owned by the integrator. Every stage module imports from here and nowhere
else for these types, so that the stages can be built and tested in isolation
and still plug together.

Trust model: ``text`` fields (transcript words, unit text, questions) are
UNTRUSTED data. IDs, timestamps and durations are generated by trusted code.
Nothing in here executes or interprets text.
"""

from __future__ import annotations

import json
import math
import time
from dataclasses import asdict, dataclass, field
from typing import Any, Callable, Dict, Iterable, List, Optional, Protocol, Tuple

# A span of audio in seconds from the start of the ORIGINAL recording.
Span = Tuple[float, float]


# --------------------------------------------------------------------------- #
# Timed transcript
# --------------------------------------------------------------------------- #

@dataclass(frozen=True)
class Word:
    """One recognised word with original-audio timing.

    ``word_id`` is unique across the whole request (global, not per unit), so a
    QA backend can refer to words without naming the unit they sit in.
    """

    word_id: int
    start_s: float
    end_s: float
    text: str
    probability: Optional[float] = None


@dataclass
class TranscriptUnit:
    """A contiguous stretch of speech: the granularity QA selects evidence at.

    Units are produced by the ASR backend (whisper segments) and then usually
    re-cut by ``transcript.resegment`` into clause-sized pieces, because gold
    evidence spans have a median length near three seconds.
    """

    unit_id: int
    start_s: float
    end_s: float
    text: str
    words: List[Word] = field(default_factory=list)
    avg_logprob: Optional[float] = None
    no_speech_prob: Optional[float] = None
    speaker: Optional[str] = None

    @property
    def duration_s(self) -> float:
        return self.end_s - self.start_s


@dataclass
class AudioContext:
    """Everything the QA and evidence stages know about one recording."""

    audio_sha256: str
    duration_s: float
    units: List[TranscriptUnit]
    asr_model_id: str = ''
    asr_config_hash: str = ''
    sample_rate: int = 16000
    timing_method: str = 'whisper_word'
    diagnostics: Dict[str, Any] = field(default_factory=dict)

    # -- lookups ---------------------------------------------------------- #

    def unit_by_id(self, unit_id: int) -> Optional[TranscriptUnit]:
        for unit in self.units:
            if unit.unit_id == unit_id:
                return unit
        return None

    def words(self) -> List[Word]:
        return [word for unit in self.units for word in unit.words]

    def word_by_id(self, word_id: int) -> Optional[Word]:
        for word in self.words():
            if word.word_id == word_id:
                return word
        return None

    def full_text(self, separator: str = ' ') -> str:
        return separator.join(unit.text.strip() for unit in self.units)

    # -- serialisation ---------------------------------------------------- #

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)

    def to_json(self, **kwargs: Any) -> str:
        return json.dumps(self.to_dict(), **kwargs)

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'AudioContext':
        units = [
            TranscriptUnit(
                unit_id=int(u['unit_id']),
                start_s=float(u['start_s']),
                end_s=float(u['end_s']),
                text=str(u['text']),
                words=[
                    Word(
                        word_id=int(w['word_id']),
                        start_s=float(w['start_s']),
                        end_s=float(w['end_s']),
                        text=str(w['text']),
                        probability=(
                            None if w.get('probability') is None
                            else float(w['probability'])
                        ),
                    )
                    for w in u.get('words', [])
                ],
                avg_logprob=u.get('avg_logprob'),
                no_speech_prob=u.get('no_speech_prob'),
                speaker=u.get('speaker'),
            )
            for u in data['units']
        ]
        return cls(
            audio_sha256=str(data['audio_sha256']),
            duration_s=float(data['duration_s']),
            units=units,
            asr_model_id=str(data.get('asr_model_id', '')),
            asr_config_hash=str(data.get('asr_config_hash', '')),
            sample_rate=int(data.get('sample_rate', 16000)),
            timing_method=str(data.get('timing_method', 'whisper_word')),
            diagnostics=dict(data.get('diagnostics', {})),
        )

    @classmethod
    def from_json(cls, text: str) -> 'AudioContext':
        return cls.from_dict(json.loads(text))


# --------------------------------------------------------------------------- #
# QA and final predictions
# --------------------------------------------------------------------------- #

@dataclass
class QAResult:
    """A QA backend's verdict on one question.

    ``evidence_unit_ids`` must be existing unit ids of the context; the
    evidence stage validates them again and never trusts them blindly.
    ``evidence_word_ids`` is an optional finer selection (global word ids).
    ``confidence`` is a diagnostic in [0, 1]; it is not calibrated unless a
    backend says so.
    """

    question_index: int
    answer: bool
    evidence_unit_ids: List[int] = field(default_factory=list)
    evidence_word_ids: Optional[List[int]] = None
    confidence: float = 0.5
    backend: str = ''
    diagnostics: Dict[str, Any] = field(default_factory=dict)


@dataclass
class Prediction:
    """The final per-question output before it becomes the wire DTO."""

    answer: bool
    span: Optional[Span]
    source: str = ''
    diagnostics: Dict[str, Any] = field(default_factory=dict)


# --------------------------------------------------------------------------- #
# Deadline
# --------------------------------------------------------------------------- #

class Deadline:
    """Monotonic per-request budget shared by every stage.

    Stages call ``fits(cost)`` before starting optional work and
    ``checkpoint(name)`` when they finish, so the pipeline can log where the
    time went. ``clock`` is injectable for tests.
    """

    def __init__(
        self,
        budget_s: float,
        clock: Callable[[], float] = time.monotonic,
        reserve_s: float = 0.0,
    ) -> None:
        self._clock = clock
        self.budget_s = float(budget_s)
        self.reserve_s = float(reserve_s)
        self.started = clock()
        self.stage_times: Dict[str, float] = {}
        self._last = self.started

    def elapsed(self) -> float:
        return self._clock() - self.started

    def remaining(self) -> float:
        return self.budget_s - self.elapsed()

    def expired(self) -> bool:
        return self.remaining() <= 0.0

    def fits(self, cost_s: float, reserve_s: Optional[float] = None) -> bool:
        reserve = self.reserve_s if reserve_s is None else reserve_s
        return self.remaining() - reserve >= cost_s

    def checkpoint(self, name: str) -> float:
        now = self._clock()
        took = now - self._last
        self.stage_times[name] = self.stage_times.get(name, 0.0) + took
        self._last = now
        return took


# --------------------------------------------------------------------------- #
# Stage protocols
# --------------------------------------------------------------------------- #

class ASRBackend(Protocol):
    """Timed transcription. Implementations live in ``asr_backend.py``."""

    model_id: str
    config_hash: str

    def warm_up(self) -> None: ...

    def transcribe(
        self,
        waveform: Any,
        sample_rate: int,
        deadline: Optional[Deadline] = None,
        cache_key: Optional[str] = None,
    ) -> List[TranscriptUnit]: ...


class QABackend(Protocol):
    """Grounded yes/no answering. Implementations live in ``qa_backend.py``
    and ``qa_llm_backend.py``."""

    name: str

    def warm_up(self) -> None: ...

    def answer(
        self,
        context: AudioContext,
        questions: List[str],
        deadline: Optional[Deadline] = None,
    ) -> List[QAResult]: ...


# --------------------------------------------------------------------------- #
# Small helpers every stage needs
# --------------------------------------------------------------------------- #

def is_finite_number(value: Any) -> bool:
    """True for a real int/float (not bool) that is finite."""
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        return False
    return math.isfinite(value)


def stable_hash(obj: Any) -> str:
    """SHA-256 of a JSON-serialisable object with sorted keys (config hashes)."""
    import hashlib

    payload = json.dumps(obj, sort_keys=True, default=str).encode('utf-8')
    return hashlib.sha256(payload).hexdigest()


def check_units(units: Iterable[TranscriptUnit], duration_s: Optional[float] = None) -> List[str]:
    """Return a list of anomaly descriptions (empty when the units are sane).

    Diagnostics only: ASR word timings are not perfectly monotonic and the
    pipeline must tolerate that, but it should know about it.
    """
    problems: List[str] = []
    seen_units, seen_words = set(), set()
    last_end = -math.inf
    for unit in units:
        if unit.unit_id in seen_units:
            problems.append(f'duplicate unit_id {unit.unit_id}')
        seen_units.add(unit.unit_id)
        if not (is_finite_number(unit.start_s) and is_finite_number(unit.end_s)):
            problems.append(f'unit {unit.unit_id}: non-finite bounds')
            continue
        if unit.end_s < unit.start_s:
            problems.append(f'unit {unit.unit_id}: end before start')
        if unit.start_s < last_end - 1e-6:
            problems.append(f'unit {unit.unit_id}: overlaps previous unit')
        if duration_s is not None and unit.end_s > duration_s + 0.5:
            problems.append(f'unit {unit.unit_id}: ends after audio duration')
        last_end = max(last_end, unit.end_s)
        for word in unit.words:
            if word.word_id in seen_words:
                problems.append(f'duplicate word_id {word.word_id}')
            seen_words.add(word.word_id)
            if word.start_s < unit.start_s - 1e-6 or word.end_s > unit.end_s + 1e-6:
                problems.append(f'word {word.word_id} outside unit {unit.unit_id}')
    return problems
